# Generated by Django 5.1.7 on 2025-03-22 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_time', models.DateTimeField(auto_now_add=True)),
                ('punch_type', models.CharField(choices=[('IN', 'Check In'), ('OUT', 'Check Out')], default='IN', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'ordering': ['-punch_time'],
            },
        ),
    ]
