# Generated by Django 5.1.7 on 2025-03-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_create_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123', max_length=128),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='punch_type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3),
        ),
    ]
