# Generated by Django 5.1.7 on 2025-03-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_specialworkingday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialworkingday',
            name='follow_timetable_of',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')]),
        ),
    ]
